server:
  http-port: ${FF_PORT:18880}
  http2:
    enabled: ${FF_HTTPS:false}
  ssl:
    enabled: ${FF_HTTPS:false}
    port: ${FF_HTTPS_PORT:18881}
    forced: ${FF_HTTPS_FORCED:true}
    certificate: file:${FF_HTTPS_CERTIFICATE:/opt/demo_project/ssl/ssl_certificate.crt}
    certificate-private-key:  file:${FF_HTTPS_CERTIFICATE_PRIVATE_KEY:/opt/demo_project/ssl/ssl_private.key}
logging:
  level:
    root: ${FF_LOG_LEVEL:INFO}
  file:
    name: ${FF_LOG_DIR:/opt/demo_project/logs}/log.log
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${FF_DATASOURCE_HOST:localhost}:${FF_DATASOURCE_PORT:5432}/${FF_DATASOURCE_DATABASE:demo_project}
    username: ${FF_DATASOURCE_USERNAME:demo_project}
    password: ${FF_DATASOURCE_PASSWORD:demo_project}
redisson:
  file: ${FF_REDIS_CONFIG_FILE:}
  host: ${FF_REDIS_HOST:localhost}
  port: ${FF_REDIS_PORT:6379}
  database: ${FF_REDIS_DATABASE:0}
  password: ${FF_REDIS_PASSWORD:redis}
security:
  secret:
    public-key: ${FF_SECRET_PUBLIC_KEY:/opt/demo_project/secret/id_ed25519.pub}
    private-key: ${FF_SECRET_PRIVATE_KEY:/opt/demo_project/secret/id_ed25519}
